/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hyperlinksSupport

import java.io.File

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val knowledgeBaseService = KnowledgeBaseService()

    val initFile = knowledgeBaseService.createKnowledgeBase()
    println(initFile.path)

    val id = initFile.parent.split(File.separator).last()
}