/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hyperlinksSupport

fun main() {
    val knowledgeBaseService = KnowledgeBaseService()

    val manager: KnowledgeBaseManager = knowledgeBaseService.createKnowledgeBase()

}